Customize scripts with cargo

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 set -e            # fail fast
-set -o pipefail   # don't ignore exit codes when piping output
+set -o pipefail   # dont ignore exit codes when piping output
 # set -x          # enable debugging
 
 build_dir=$1
@@ -12,42 +12,20 @@ buildpack_dir=$(cd $(dirname $0); cd ..; pwd)
 # Load some convenience functions like status(), echo(), and indent()
 source $buildpack_dir/bin/common.sh
 
-export_env_dir $env_dir
-build_env=${EMBER_ENV:-production}
+status "Installing rust and cargo"
+curl -O http://people.mozilla.org/~acrichton/rust-0.12.0-pre-x86_64-unknown-linux-gnu.tar.gz
+curl -O http://static.rust-lang.org/cargo-dist/cargo-nightly-linux.tar.gz
 
-mkdir -p $build_dir/vendor
+tar xf rust-0.12.0-pre-x86_64-unknown-linux-gnu.tar.gz
+tar xf cargo-nightly-linux.tar.gz
+./rust-0.12.0-pre-x86_64-unknown-linux-gnu/install.sh
+./cargo-nightly/install.sh
 
-status "Downloading and installing node"
-node_version=0.10.29
-node_url=http://s3pository.heroku.com/node/v$node_version/node-v$node_version-linux-x64.tar.gz
-curl $node_url -s -o - | tar xzf - -C $build_dir
-mv $build_dir/node-v$node_version-linux-x64 $build_dir/vendor/node
-chmod +x $build_dir/vendor/node/bin/*
-PATH=$build_dir/vendor/node/bin:$PATH
-
-status "Downloading and installing nginx"
-nginx_url=http://www.brettwhitelaw.com/pkg/nginx-1.6.0.tar.gz
-curl $nginx_url -s -o - | tar xzf - -C $build_dir/vendor
-
-status "Adding boot script"
-cp $buildpack_dir/bin/boot.sh $build_dir
-
-status "Copying configs"
-mkdir -p $build_dir/config
-cp $buildpack_dir/config/mime.types $build_dir/config
-if [[ ! -f $build_dir/config/nginx.conf.erb ]]; then
-  cp $buildpack_dir/config/nginx.conf.erb $build_dir/config
-else
-  status "Custom nginx config found"
-fi
+status "Testing if rust was installed"
+rustc --version
+cargo --version
 
 cd $build_dir
 
-status "Installing dependencies"
-trap cat_npm_debug_log ERR # Output npm debug info on error
-npm install bower --quiet | indent
-npm install --quiet | indent
-
-status "Building Ember CLI application $build_env distribution"
-node_modules/.bin/bower install --quiet | indent
-node_modules/ember-cli/bin/ember build --environment $build_env | indent
+status "Building app"
+cargo build
